#!/usr/bin/env python
# encoding: utf-8

APPNAME = 'libp60-client'

top = '.'
out = 'build'

def options(ctx):
    gr = ctx.add_option_group('NanoPower-P60 library client options')
    gr.add_option('--disable-libp60-cmd', action='store_true', help='Disable client cmd code for NanoPower-P60 library')

def configure(ctx):
    ctx.env.append_unique('FILES_LIBP60_CLIENT', ['power_if.c'])
    if not ctx.options.disable_libp60_cmd:
        ctx.env.append_unique('FILES_LIBP60_CLIENT', ['power_if_cmd.c'])

def build(ctx):
    ctx(export_includes=['.'], name=APPNAME)
    ctx.objects(
        source = ctx.path.ant_glob(ctx.env.FILES_LIBP60_CLIENT),
        target = APPNAME,
        includes = '.',
        export_includes = '.',
        use = ['csp', 'gosh', 'param']
    )
