#!/usr/bin/env python
# encoding: utf-8

APPNAME = 'p60-pdu-client'

top = '.'
pdu = 'build'

def options(ctx):
    gr = ctx.add_option_group('NanoPower-P60 PDU client options')
    gr.add_option('--disable-p60-pdu-cmd', action='store_true', help='Disable client cmd code for NanoPower-P60 PDU')

def configure(ctx):
    ctx.env.append_unique('FILES_P60_PDU_CLIENT', ['p60pdu_client.c'])
    if not ctx.options.disable_p60_pdu_cmd:
        ctx.env.append_unique('FILES_P60_PDU_CLIENT', ['p60pdu_cmd.c'])

def build(ctx):
    ctx.objects(
        source = ctx.path.ant_glob(ctx.env.FILES_P60_PDU_CLIENT),
        target = APPNAME,
        includes = '.',
        export_includes = '.',
        use = ['csp', 'gosh', 'param', 'libp60-client']
    )
