#!/usr/bin/env python
# encoding: utf-8

APPNAME = 'p60-dock-client'

top = '.'
out = 'build'

def options(ctx):
    gr = ctx.add_option_group('NanoPower-P60 Dock client options')
    gr.add_option('--disable-p60-dock-cmd', action='store_true', help='Disable client cmd code for NanoPower-P60 Dock')

def configure(ctx):
    ctx.env.append_unique('FILES_P60_DOCK_CLIENT', ['p60dock_client.c'])
    if not ctx.options.disable_p60_dock_cmd:
        ctx.env.append_unique('FILES_P60_DOCK_CLIENT', ['p60dock_cmd.c'])

def build(ctx):
    ctx.objects(
        source = ctx.path.ant_glob(ctx.env.FILES_P60_DOCK_CLIENT),
        target = APPNAME,
        includes = '.',
        export_includes = '.',
        use = ['csp', 'gosh', 'param', 'libp60-client']
    )
