#!/usr/bin/env python
# encoding: utf-8

import os
import time

APPNAME = 'libgssb-client'

top	= '.'
out	= 'build'

def options(ctx):
	pass
	
def configure(ctx):
	pass
	
def build(ctx):
	ctx.objects(
		source = ctx.path.ant_glob('*.c'), 
		target = APPNAME,
		includes = '.',
		export_includes = '.',
		use = ['csp', 'util', 'gosh']
	)
