#include <gomx3_adcs_hk.h>
#include <hk_types.h>

int hk_adcs_init_telem1(void) {return 0;}
int hk_adcs_init_telem2(void) {return 0;}
int hk_adcs_init_telem3(void) {return 0;}
int hk_adcs_init_telem4(void) {return 0;}
int hk_adcs_init_telem5(void) {return 0;}
int hk_adcs_init_telem6(void) {return 0;}
int hk_adcs_collect_telem1(void) {return 0;}
int hk_adcs_collect_telem2(void) {return 0;}
int hk_adcs_collect_telem3(void) {return 0;}
int hk_adcs_collect_telem4(void) {return 0;}
int hk_adcs_collect_telem5(void) {return 0;}
int hk_adcs_collect_telem6(void) {return 0;}

hk_table_t adcs_hk_tables[] = {
	{
		.node = 4,
		.tableid = A3200_BOARD,
		.memid = PARAM_INDEX_A3200_BOARD_ADCS,
		.table = a3200_config,
		.count = A3200_CONFIG_COUNT,
		.size = A3200_MEM_SIZE,
		.nodename = "adcs",
		.param_interval = GOMX3_HK_INTV_ADCS_BOARD,
	},{
		.node = 4,
		.tableid = PARAM_ADCS_TELEM1,
		.memid = PARAM_ADCS_TELEM1,
		.table = adcs_param_telem1,
		.count = ADCS_PARAM_TELEM1_COUNT,
		.size = ADCS_PARAM_TELEM1_MEMSIZE,
		.nodename = "adcs1",
		.param_interval = GOMX3_HK_INTV_ADCS_TELEM1,
		.init_fct = hk_adcs_init_telem1,
		.collect_fct = hk_adcs_collect_telem1,
	},{
		.node = 4,
		.tableid = PARAM_ADCS_TELEM2,
		.memid = PARAM_ADCS_TELEM2,
		.table = adcs_param_telem2,
		.count = ADCS_PARAM_TELEM2_COUNT,
		.size = ADCS_PARAM_TELEM2_MEMSIZE,
		.nodename = "adcs2",
		.param_interval = GOMX3_HK_INTV_ADCS_TELEM2,
		.init_fct = hk_adcs_init_telem2,
		.collect_fct = hk_adcs_collect_telem2,
	},{
		.node = 4,
		.tableid = PARAM_ADCS_TELEM3,
		.memid = PARAM_ADCS_TELEM3,
		.table = adcs_param_telem3,
		.count = ADCS_PARAM_TELEM3_COUNT,
		.size = ADCS_PARAM_TELEM3_MEMSIZE,
		.nodename = "adcs3",
		.param_interval = GOMX3_HK_INTV_ADCS_TELEM3,
		.init_fct = hk_adcs_init_telem3,
		.collect_fct = hk_adcs_collect_telem3,
	},{
		.node = 4,
		.tableid = PARAM_ADCS_TELEM4,
		.memid = PARAM_ADCS_TELEM4,
		.table = adcs_param_telem4,
		.count = ADCS_PARAM_TELEM4_COUNT,
		.size = ADCS_PARAM_TELEM4_MEMSIZE,
		.nodename = "adcs4",
		.param_interval = GOMX3_HK_INTV_ADCS_TELEM4,
		.init_fct = hk_adcs_init_telem4,
		.collect_fct = hk_adcs_collect_telem4,
	},{
		.node = 4,
		.tableid = PARAM_ADCS_TELEM5,
		.memid = PARAM_ADCS_TELEM5,
		.table = adcs_param_telem5,
		.count = ADCS_PARAM_TELEM5_COUNT,
		.size = ADCS_PARAM_TELEM5_MEMSIZE,
		.nodename = "adcs5",
		.param_interval = GOMX3_HK_INTV_ADCS_TELEM5,
		.init_fct = hk_adcs_init_telem5,
		.collect_fct = hk_adcs_collect_telem5,
	},{
		.node = 4,
		.tableid = PARAM_ADCS_TELEM6,
		.memid = PARAM_ADCS_TELEM6,
		.table = adcs_param_telem6,
		.count = ADCS_PARAM_TELEM6_COUNT,
		.size = ADCS_PARAM_TELEM6_MEMSIZE,
		.nodename = "adcs6",
		.param_interval = GOMX3_HK_INTV_ADCS_TELEM6,
		.init_fct = hk_adcs_init_telem6,
		.collect_fct = hk_adcs_collect_telem6,
	}
};

/**
 */
static const uint16_t hk_beacon_format_0[] = {

	0x8000 | PARAM_ADCS_TELEM1,
	ADCS_TELEM1_EXTMAG_TEMP,
	ADCS_TELEM1_SUNS_TEMP(0),
	ADCS_TELEM1_SUNS_TEMP(1),
	ADCS_TELEM1_SUNS_TEMP(2),
	ADCS_TELEM1_SUNS_TEMP(3),
	ADCS_TELEM1_SUNS_TEMP(4),
	ADCS_TELEM1_SUNS_TEMP(5),
	ADCS_TELEM1_GYRO_TEMP,

	ADCS_TELEM1_MAG(0),
	ADCS_TELEM1_MAG(1),
	ADCS_TELEM1_MAG(2),
	ADCS_TELEM1_MAG_VALID,
	ADCS_TELEM1_EXTMAG(0),
	ADCS_TELEM1_EXTMAG(1),
	ADCS_TELEM1_EXTMAG(2),
	ADCS_TELEM1_EXTMAG_VALID,
	ADCS_TELEM1_SUNS(0),
	ADCS_TELEM1_SUNS(1),
	ADCS_TELEM1_SUNS(3),
	ADCS_TELEM1_SUNS(4),
	ADCS_TELEM1_SUNS(5),
	ADCS_TELEM1_SUNS_VALID,
	ADCS_TELEM1_GYRO(0),
	ADCS_TELEM1_GYRO(1),
	ADCS_TELEM1_GYRO(2),
	ADCS_TELEM1_GYRO_TREND(0),
	ADCS_TELEM1_GYRO_TREND(1),
	ADCS_TELEM1_GYRO_TREND(2),
	ADCS_TELEM1_GYRO_VALID,

	ADCS_TELEM1_TORQUERDUTY(0),
	ADCS_TELEM1_TORQUERDUTY(1),
	ADCS_TELEM1_TORQUERDUTY(2),

	0x8000 | PARAM_ADCS_TELEM2,
	ADCS_TELEM2_STA_MAG,
	ADCS_TELEM2_STA_EXTMAG,
	ADCS_TELEM2_STA_CSS,
	ADCS_TELEM2_STA_GYRO,
	ADCS_TELEM2_STA_BDOT,
	ADCS_TELEM2_STA_RUN,
	ADCS_TELEM2_TLOOP,
	ADCS_TELEM2_MAXTLOOP,

	ADCS_TELEM2_BDOT_RATE(0),
	ADCS_TELEM2_BDOT_RATE(1),
	ADCS_TELEM2_BDOT_DMAG(0),
	ADCS_TELEM2_BDOT_DMAG(1),
	ADCS_TELEM2_BDOT_DMAG(2),
	ADCS_TELEM2_BDOT_DETUMBLED,

	ADCS_TELEM2_ACS_MODE,
	ADCS_TELEM2_ACS_DMODE,
	ADCS_TELEM2_ADS_MODE,
	ADCS_TELEM2_ADS_DMODE,
	ADCS_TELEM2_EPHEM_MODE,
	ADCS_TELEM2_EPHEM_DMODE,
};



/**
 */
static const uint16_t hk_beacon_format_1[] = {

	0x8000 | PARAM_ADCS_TELEM1,

	ADCS_TELEM1_FSS(0, 0),
	ADCS_TELEM1_FSS(0, 1),
	ADCS_TELEM1_FSS(0, 2),
	ADCS_TELEM1_FSS(1, 0),
	ADCS_TELEM1_FSS(1, 1),
	ADCS_TELEM1_FSS(1, 2),
	ADCS_TELEM1_FSS(2, 0),
	ADCS_TELEM1_FSS(2, 1),
	ADCS_TELEM1_FSS(2, 2),
	ADCS_TELEM1_FSS(3, 0),
	ADCS_TELEM1_FSS(3, 1),
	ADCS_TELEM1_FSS(3, 2),
	ADCS_TELEM1_FSS(4, 0),
	ADCS_TELEM1_FSS(4, 1),
	ADCS_TELEM1_FSS(4, 2),
	ADCS_TELEM1_FSS(5, 0),
	ADCS_TELEM1_FSS(5, 1),
	ADCS_TELEM1_FSS(5, 2),
	ADCS_TELEM1_FSS(6, 0),
	ADCS_TELEM1_FSS(6, 1),
	ADCS_TELEM1_FSS(6, 2),
	ADCS_TELEM1_FSS(7, 0),
	ADCS_TELEM1_FSS(7, 1),
	ADCS_TELEM1_FSS(7, 2),

	ADCS_TELEM1_FSS_TEMP(0),
	ADCS_TELEM1_FSS_TEMP(1),
	ADCS_TELEM1_FSS_TEMP(2),
	ADCS_TELEM1_FSS_TEMP(3),
	ADCS_TELEM1_FSS_TEMP(4),
	ADCS_TELEM1_FSS_TEMP(5),
	ADCS_TELEM1_FSS_TEMP(6),
	ADCS_TELEM1_FSS_TEMP(7),

	0x8000 | PARAM_ADCS_TELEM2,

	ADCS_TELEM2_STA_FSS(0),
	ADCS_TELEM2_STA_FSS(1),
	ADCS_TELEM2_STA_FSS(2),
	ADCS_TELEM2_STA_FSS(3),
	ADCS_TELEM2_STA_FSS(4),
	ADCS_TELEM2_STA_FSS(5),
	ADCS_TELEM2_STA_FSS(6),
	ADCS_TELEM2_STA_FSS(7),
};

/**
 */
static const uint16_t hk_beacon_format_2[] = {

		0x8000 | PARAM_ADCS_TELEM3,
		ADCS_TELEM3_UKF_X(0),
		ADCS_TELEM3_UKF_X(1),
		ADCS_TELEM3_UKF_X(2),
		ADCS_TELEM3_UKF_X(3),
		ADCS_TELEM3_UKF_X(4),
		ADCS_TELEM3_UKF_X(5),
		ADCS_TELEM3_UKF_X(6),
		ADCS_TELEM3_UKF_X(7),
		ADCS_TELEM3_UKF_X(8),
		ADCS_TELEM3_UKF_X(9),
		ADCS_TELEM3_UKF_X(10),
		ADCS_TELEM3_UKF_X(11),
		ADCS_TELEM3_UKF_X(12),

		ADCS_TELEM3_UKF_PDIAG(0),
		ADCS_TELEM3_UKF_PDIAG(1),
		ADCS_TELEM3_UKF_PDIAG(2),
		ADCS_TELEM3_UKF_PDIAG(3),
		ADCS_TELEM3_UKF_PDIAG(4),
		ADCS_TELEM3_UKF_PDIAG(5),
		ADCS_TELEM3_UKF_PDIAG(6),
		ADCS_TELEM3_UKF_PDIAG(7),
		ADCS_TELEM3_UKF_PDIAG(8),
		ADCS_TELEM3_UKF_PDIAG(9),
		ADCS_TELEM3_UKF_PDIAG(10),
		ADCS_TELEM3_UKF_PDIAG(11),

		ADCS_TELEM3_UKF_ZPRED(0),
		ADCS_TELEM3_UKF_ZPRED(1),
		ADCS_TELEM3_UKF_ZPRED(2),
		ADCS_TELEM3_UKF_ZPRED(3),
		ADCS_TELEM3_UKF_ZPRED(4),
		ADCS_TELEM3_UKF_ZPRED(5),
		ADCS_TELEM3_UKF_ZPRED(6),
		ADCS_TELEM3_UKF_ZPRED(7),
		ADCS_TELEM3_UKF_ZPRED(8),
		ADCS_TELEM3_UKF_ZPRED(9),
		ADCS_TELEM3_UKF_ZPRED(10),
		ADCS_TELEM3_UKF_ZPRED(11),

		ADCS_TELEM3_UKF_INECLIPSE,

		0x8000 | PARAM_ADCS_TELEM4,
		ADCS_TELEM4_EPHEM_JULIANDATE,
		ADCS_TELEM4_EPHEM_RECI(0),
		ADCS_TELEM4_EPHEM_RECI(1),
		ADCS_TELEM4_EPHEM_RECI(2),
		ADCS_TELEM4_EPHEM_VECI(0),
		ADCS_TELEM4_EPHEM_VECI(1),
		ADCS_TELEM4_EPHEM_VECI(2),


		0x8000 | PARAM_ADCS_TELEM2,
		ADCS_TELEM2_STA_UKF,
		ADCS_TELEM2_STA_SGP4,
		ADCS_TELEM2_STA_IGRF,
};

/**

 */
static const uint16_t hk_beacon_format_3[] = {

	0x8000 | PARAM_ADCS_TELEM5,
	ADCS_TELEM5_CTRL_REFQ(0),
	ADCS_TELEM5_CTRL_REFQ(1),
	ADCS_TELEM5_CTRL_REFQ(2),
	ADCS_TELEM5_CTRL_REFQ(3),
	ADCS_TELEM5_CTRL_ERRQ(0),
	ADCS_TELEM5_CTRL_ERRQ(1),
	ADCS_TELEM5_CTRL_ERRQ(2),
	ADCS_TELEM5_CTRL_ERRQ(3),
	ADCS_TELEM5_CTRL_ERRRATE(0),
	ADCS_TELEM5_CTRL_ERRRATE(1),
	ADCS_TELEM5_CTRL_ERRRATE(2),

	ADCS_TELEM5_CTRL_M(0),
	ADCS_TELEM5_CTRL_M(1),
	ADCS_TELEM5_CTRL_M(2),

	ADCS_TELEM5_CTRL_MWSPEED(0),
	ADCS_TELEM5_CTRL_MWSPEED(1),
	ADCS_TELEM5_CTRL_MWSPEED(2),
	ADCS_TELEM5_CTRL_MWSPEED(3),

	ADCS_TELEM5_CTRL_MWTORQUE(0),
	ADCS_TELEM5_CTRL_MWTORQUE(1),
	ADCS_TELEM5_CTRL_MWTORQUE(2),
	ADCS_TELEM5_CTRL_MWTORQUE(3),


	0x8000 | PARAM_ADCS_TELEM1,
	ADCS_TELEM1_TORQUERDUTY(0),
	ADCS_TELEM1_TORQUERDUTY(1),
	ADCS_TELEM1_TORQUERDUTY(2),

	ADCS_TELEM1_WHEELSPEED(0),
	ADCS_TELEM1_WHEELSPEED(1),
	ADCS_TELEM1_WHEELSPEED(2),
	ADCS_TELEM1_WHEELSPEED(3),

	0x8000 | PARAM_ADCS_TELEM2,
	ADCS_TELEM2_YSPIN_MODE,

	0x8000 | PARAM_ADCS_TELEM3,
	ADCS_TELEM3_UKF_Q(0),
	ADCS_TELEM3_UKF_Q(1),
	ADCS_TELEM3_UKF_Q(2),
	ADCS_TELEM3_UKF_Q(3),
	ADCS_TELEM3_UKF_RATE(0),
	ADCS_TELEM3_UKF_RATE(1),
	ADCS_TELEM3_UKF_RATE(2),

	0x8000 | PARAM_ADCS_TELEM4,
	ADCS_TELEM4_EPHEM_RECI(0),
	ADCS_TELEM4_EPHEM_RECI(1),
	ADCS_TELEM4_EPHEM_RECI(2),
	ADCS_TELEM4_EPHEM_VECI(0),
	ADCS_TELEM4_EPHEM_VECI(1),
	ADCS_TELEM4_EPHEM_VECI(2),
};



/**

 */
static const uint16_t hk_beacon_format_4[] = {


	0x8000 | PARAM_ADCS_TELEM1,
	ADCS_TELEM1_GPS_POS(0),
	ADCS_TELEM1_GPS_POS(1),
	ADCS_TELEM1_GPS_POS(2),
	ADCS_TELEM1_GPS_VEL(0),
	ADCS_TELEM1_GPS_VEL(1),
	ADCS_TELEM1_GPS_VEL(2),
	ADCS_TELEM1_GPS_EPOCH,
	ADCS_TELEM1_GPS_JULIAN,
	ADCS_TELEM1_GPS_VALID,

	0x8000 | PARAM_ADCS_TELEM4,
	ADCS_TELEM4_J2_EPOCH,
	ADCS_TELEM4_J2_PECI(0),
	ADCS_TELEM4_J2_PECI(1),
	ADCS_TELEM4_J2_PECI(2),
	ADCS_TELEM4_J2_VECI(0),
	ADCS_TELEM4_J2_VECI(1),
	ADCS_TELEM4_J2_VECI(2),
	ADCS_TELEM4_J2_A,
	ADCS_TELEM4_J2_N,
	ADCS_TELEM4_J2_P,
	ADCS_TELEM4_J2_INCL,
	ADCS_TELEM4_J2_RAAN,
	ADCS_TELEM4_J2_ARGPER,
	ADCS_TELEM4_J2_TRUEANOM,
	ADCS_TELEM4_J2_ECCANOM,
	ADCS_TELEM4_J2_MEANANOM,

	0x8000 | PARAM_ADCS_TELEM2,
	ADCS_TELEM2_STA_GPS,
	ADCS_TELEM2_STA_J2ELE,
	ADCS_TELEM2_STA_J2PRO,
};


/**

 */
static const uint16_t hk_beacon_format_5[] = {

		0x8000 | PARAM_ADCS_TELEM1,
		ADCS_TELEM1_FSS_RAW(0, 0),
		ADCS_TELEM1_FSS_RAW(0, 1),
		ADCS_TELEM1_FSS_RAW(0, 2),
		ADCS_TELEM1_FSS_RAW(0, 3),
		ADCS_TELEM1_FSS_RAW(1, 0),
		ADCS_TELEM1_FSS_RAW(1, 1),
		ADCS_TELEM1_FSS_RAW(1, 2),
		ADCS_TELEM1_FSS_RAW(1, 3),
		ADCS_TELEM1_FSS_RAW(2, 0),
		ADCS_TELEM1_FSS_RAW(2, 1),
		ADCS_TELEM1_FSS_RAW(2, 2),
		ADCS_TELEM1_FSS_RAW(2, 3),
		ADCS_TELEM1_FSS_RAW(3, 0),
		ADCS_TELEM1_FSS_RAW(3, 1),
		ADCS_TELEM1_FSS_RAW(3, 2),
		ADCS_TELEM1_FSS_RAW(3, 3),
		ADCS_TELEM1_FSS_RAW(4, 0),
		ADCS_TELEM1_FSS_RAW(4, 1),
		ADCS_TELEM1_FSS_RAW(4, 2),
		ADCS_TELEM1_FSS_RAW(4, 3),
		ADCS_TELEM1_FSS_RAW(5, 0),
		ADCS_TELEM1_FSS_RAW(5, 1),
		ADCS_TELEM1_FSS_RAW(5, 2),
		ADCS_TELEM1_FSS_RAW(5, 3),
		ADCS_TELEM1_FSS_RAW(6, 0),
		ADCS_TELEM1_FSS_RAW(6, 1),
		ADCS_TELEM1_FSS_RAW(6, 2),
		ADCS_TELEM1_FSS_RAW(6, 3),
		ADCS_TELEM1_FSS_RAW(7, 0),
		ADCS_TELEM1_FSS_RAW(7, 1),
		ADCS_TELEM1_FSS_RAW(7, 2),
		ADCS_TELEM1_FSS_RAW(7, 3),
		ADCS_TELEM1_FSS_TEMP(0),
		ADCS_TELEM1_FSS_TEMP(1),
		ADCS_TELEM1_FSS_TEMP(2),
		ADCS_TELEM1_FSS_TEMP(3),
		ADCS_TELEM1_FSS_TEMP(4),
		ADCS_TELEM1_FSS_TEMP(5),
		ADCS_TELEM1_FSS_TEMP(6),
		ADCS_TELEM1_FSS_TEMP(7),

		0x8000 | PARAM_ADCS_TELEM2,

		ADCS_TELEM2_STA_FSS(0),
		ADCS_TELEM2_STA_FSS(1),
		ADCS_TELEM2_STA_FSS(2),
		ADCS_TELEM2_STA_FSS(3),
		ADCS_TELEM2_STA_FSS(4),
		ADCS_TELEM2_STA_FSS(5),
		ADCS_TELEM2_STA_FSS(6),
		ADCS_TELEM2_STA_FSS(7),
};

/**

 */
static const uint16_t hk_beacon_format_6[] = {
		0x8000 | PARAM_ADCS_TELEM6,
		ADCS_TELEM6_HTPA0_PTAT,
		ADCS_TELEM6_HTPA0_PTAT_COMP,
		ADCS_TELEM6_HTPA0_RAW0(0),
		ADCS_TELEM6_HTPA0_RAW0(1),
		ADCS_TELEM6_HTPA0_RAW0(2),
		ADCS_TELEM6_HTPA0_RAW0(3),
		ADCS_TELEM6_HTPA0_RAW0(4),
		ADCS_TELEM6_HTPA0_RAW0(5),
		ADCS_TELEM6_HTPA0_RAW0(6),
		ADCS_TELEM6_HTPA0_RAW0(7),
		ADCS_TELEM6_HTPA0_RAW0(8),
		ADCS_TELEM6_HTPA0_RAW0(9),
		ADCS_TELEM6_HTPA0_RAW0(10),
		ADCS_TELEM6_HTPA0_RAW0(11),
		ADCS_TELEM6_HTPA0_RAW0(12),
		ADCS_TELEM6_HTPA0_RAW0(13),
		ADCS_TELEM6_HTPA0_RAW0(14),
		ADCS_TELEM6_HTPA0_RAW0(15),
		ADCS_TELEM6_HTPA0_RAW0(16),
		ADCS_TELEM6_HTPA0_RAW0(17),
		ADCS_TELEM6_HTPA0_RAW0(18),
		ADCS_TELEM6_HTPA0_RAW0(19),
		ADCS_TELEM6_HTPA0_RAW0(20),
		ADCS_TELEM6_HTPA0_RAW0(21),
		ADCS_TELEM6_HTPA0_RAW0(22),
		ADCS_TELEM6_HTPA0_RAW0(23),
		ADCS_TELEM6_HTPA0_RAW0(24),
		ADCS_TELEM6_HTPA0_RAW0(25),
		ADCS_TELEM6_HTPA0_RAW0(26),
		ADCS_TELEM6_HTPA0_RAW0(27),
		ADCS_TELEM6_HTPA0_RAW0(28),
		ADCS_TELEM6_HTPA0_RAW0(29),
		ADCS_TELEM6_HTPA0_RAW0(30),
		ADCS_TELEM6_HTPA0_RAW0(31),
		ADCS_TELEM6_HTPA0_RAW0(0),
			ADCS_TELEM6_HTPA0_RAW1(1),
			ADCS_TELEM6_HTPA0_RAW1(2),
			ADCS_TELEM6_HTPA0_RAW1(3),
			ADCS_TELEM6_HTPA0_RAW1(4),
			ADCS_TELEM6_HTPA0_RAW1(5),
			ADCS_TELEM6_HTPA0_RAW1(6),
			ADCS_TELEM6_HTPA0_RAW1(7),
			ADCS_TELEM6_HTPA0_RAW1(8),
			ADCS_TELEM6_HTPA0_RAW1(9),
			ADCS_TELEM6_HTPA0_RAW1(10),
			ADCS_TELEM6_HTPA0_RAW1(11),
			ADCS_TELEM6_HTPA0_RAW1(12),
			ADCS_TELEM6_HTPA0_RAW1(13),
			ADCS_TELEM6_HTPA0_RAW1(14),
			ADCS_TELEM6_HTPA0_RAW1(15),
			ADCS_TELEM6_HTPA0_RAW1(16),
			ADCS_TELEM6_HTPA0_RAW1(17),
			ADCS_TELEM6_HTPA0_RAW1(18),
			ADCS_TELEM6_HTPA0_RAW1(19),
			ADCS_TELEM6_HTPA0_RAW1(20),
			ADCS_TELEM6_HTPA0_RAW1(21),
			ADCS_TELEM6_HTPA0_RAW1(22),
			ADCS_TELEM6_HTPA0_RAW1(23),
			ADCS_TELEM6_HTPA0_RAW1(24),
			ADCS_TELEM6_HTPA0_RAW1(25),
			ADCS_TELEM6_HTPA0_RAW1(26),
			ADCS_TELEM6_HTPA0_RAW1(27),
			ADCS_TELEM6_HTPA0_RAW1(28),
			ADCS_TELEM6_HTPA0_RAW1(29),
			ADCS_TELEM6_HTPA0_RAW1(30),
			ADCS_TELEM6_HTPA0_RAW1(31),
};


hk_beacon_t adcs_hk_beacons[] = {
	{ .addrs = hk_beacon_format_0, .count = sizeof(hk_beacon_format_0) / sizeof(hk_beacon_format_0[0]), .param_interval = GOMX3_HK_BCN_INTERVAL_ADCS(0) },
	{ .addrs = hk_beacon_format_1, .count = sizeof(hk_beacon_format_1) / sizeof(hk_beacon_format_1[0]), .param_interval = GOMX3_HK_BCN_INTERVAL_ADCS(1) },
	{ .addrs = hk_beacon_format_2, .count = sizeof(hk_beacon_format_2) / sizeof(hk_beacon_format_2[0]), .param_interval = GOMX3_HK_BCN_INTERVAL_ADCS(2) },
	{ .addrs = hk_beacon_format_3, .count = sizeof(hk_beacon_format_3) / sizeof(hk_beacon_format_3[0]), .param_interval = GOMX3_HK_BCN_INTERVAL_ADCS(3) },
	{ .addrs = hk_beacon_format_4, .count = sizeof(hk_beacon_format_4) / sizeof(hk_beacon_format_4[0]), .param_interval = GOMX3_HK_BCN_INTERVAL_ADCS(4) },
	{ .addrs = hk_beacon_format_5, .count = sizeof(hk_beacon_format_5) / sizeof(hk_beacon_format_5[0]), .param_interval = GOMX3_HK_BCN_INTERVAL_ADCS(5) },
	{ .addrs = hk_beacon_format_6, .count = sizeof(hk_beacon_format_6) / sizeof(hk_beacon_format_6[0]), .param_interval = GOMX3_HK_BCN_INTERVAL_ADCS(6) },
};
